# Generated by Django 4.0.3 on 2022-03-10 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pessoa',
            new_name='Person',
        ),
    ]
